### ISSUE TITLE
"reason" : "Required [_type]"

### ISSUE THREAD

**Issue by ngelll** [rkernutt/oss_migration#1]
https://www.elastic.co/cn/blog/how-to-migrate-from-opensearch-to-elastic-cloud
I followed the document to make the configuration, but received the following error:

POST _reindex
{
    "source": {
        "remote": {
            "host": "https://search-opensearch01-nxxxxxxxxxxxstdpbzy4.us-east-1.es.amazonaws.com:443",
            "username": "xxxx",
            "password": "xxxxxxxx"
        },
        "index": "movies"
    },
    "dest": {
        "index": "moviesES"
    }
}

Opensearch info:
version: OpenSearch 2.5
R20230308-P2 
{
  "error" : {
    "root_cause" : [
      {
        "type" : "exception",
        "reason" : "Error parsing the response, remote is likely not an Elasticsearch instance"
      }
    ],
    "type" : "exception",
    "reason" : "Error parsing the response, remote is likely not an Elasticsearch instance",
    "caused_by" : {
      "type" : "x_content_parse_exception",
      "reason" : "[1:817] [search_response] failed to parse field [hits]",
      "caused_by" : {
        "type" : "x_content_parse_exception",
        "reason" : "[1:817] [hits] failed to parse field [hits]",
        "caused_by" : {
          "type" : "illegal_argument_exception",
          "reason" : "Required [_type]"
        }
      }
    }
  },
  "status" : 500
}

**Comment by rkernutt** [comment]
Hi, this error is because of duplicate fields.
Please refer to the forum discussion for details:
https://discuss.elastic.co/t/duplicate-field-during-reindex/193534
